apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: network-fzotifeztnjm
  namespace: ns-gc40gxwh
spec:
  tls:
    - hosts: [xozqlkdilqkd.sealosgzg.site]
      secretName: wildcard-cert
  rules:
    - host: xozqlkdilqkd.sealosgzg.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: widget-demo-zpnwdnljhyqs
                port: { number: 80 }
